// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Consultorio_Dentista.Model.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Cpf { get; set; }

    public DateTime DataNascimento { get; set; }

    public string NomeResp { get; set; }

    public string Telefone { get; set; }

    public string Email { get; set; }

    public string Logradouro { get; set; }

    public string Numero { get; set; }

    public string Cep { get; set; }

    public string Bairro { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Consultas> Consultas { get; set; } = new List<Consultas>();
}