// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Consultorio_Dentista.Model.Models;

public partial class Consultas
{
    public int Id { get; set; }
    [DisplayName("Cod Cliente")]
    public int IdCliente { get; set; }
    [DisplayName("Data e Hora")]
    public DateTime DataConsulta { get; set; }
    [DisplayName("Descrição")]
    public string Descricao { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }
}