// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Consultorio_Dentista.Model.Models;

public partial class Estoque
{
    public int Id { get; set; }

    public string NomeProduto { get; set; }

    public int Quantidade { get; set; }

    public decimal? PrecoUnitario { get; set; }

    public string Fornecedor { get; set; }

    public int? Perecivel { get; set; }

    public DateTime? DataValidade { get; set; }
}